Repository huynguyen-and-friend-projects/smoldb, pull requests merged in 2024-06, with the labels that each got.

#17 FIX: CMake doesn't recognize MSYS
  CMakeLists.txt
Labels: bug, help wanted

#12 feat(template): create issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#18 fix; add windows smoldb.exe file to gitignore
  .gitignore
Labels: bug, enhancement

#19 Update documentation, and CMakeLists
  CMakeLists.txt
  docs/dev-env.md
Labels: documentation, enhancement

#21 Add an index page
  docs/index.html
Labels: documentation, enhancement
